apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: data
type: Opaque
stringData:
  # Must match `vault.server.dev.devRootToken` in `../vault/values.yaml`.
  token: pass_heritage
