apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-auth
  namespace: data
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: heritage/redis
  refreshAfter: 30s
  destination:
    name: heritage-redis-auth
    create: true
    overwrite: true
