apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-auth
  namespace: data
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: heritage/postgres
  refreshAfter: 30s
  destination:
    name: heritage-postgres-auth
    create: true
    overwrite: true
