apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heritage-external-access
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: default
  source:
    repoURL: git@github.com:Zakharden/heritage-infra.git
    targetRevision: HEAD
    path: heritage-k8s-helm-charts/external-access
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
