apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heritage-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: git@github.com:Zakharden/heritage-infra.git
    targetRevision: HEAD
    path: heritage-k8s-helm-charts/redis
    helm:
      releaseName: heritage-redis
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
