[all]
vm-k8s-m1 ansible_host=52.20.233.48 ip=172.31.70.213
vm-k8s-w1 ansible_host=34.194.182.115 ip=172.31.17.45
vm-k8s-w2 ansible_host=23.23.33.244 ip=172.31.59.144

[all:vars]
ansible_user=ec2-user
ansible_become=true
ansible_become_method=sudo
ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube_control_plane]
vm-k8s-m1

[etcd]
vm-k8s-m1

[kube_node]
vm-k8s-w1
vm-k8s-w2

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr

[bastion]
