apiVersion: v2
name: heritage-postgres
description: Wrapper chart for PostgreSQL primary+replica topology
type: application
version: 0.1.0
appVersion: "16"
dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: "https://charts.bitnami.com/bitnami"
