postgresql:
  architecture: replication

  auth:
    enablePostgresUser: true
    username: app_user
    database: app_db
    existingSecret: heritage-postgres-auth
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      replicationPasswordKey: replication-password

  primary:
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi

  readReplicas:
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi
