vault:
  global:
    tlsDisable: true

  server:
    dev:
      enabled: true
      devRootToken: pass_heritage
    standalone:
      enabled: false
    ha:
      enabled: false

  injector:
    enabled: false

  csi:
    enabled: false

  ui:
    enabled: true
