[all]
vm-k8s-m1 ansible_host=52.20.233.48 ip=172.31.70.213 node_role=master,infra
vm-k8s-w1 ansible_host=34.194.182.115 ip=172.31.17.45 node_role=worker
vm-k8s-w2 ansible_host=23.23.33.244 ip=172.31.59.144 node_role=worker

[master]
vm-k8s-m1

[workers]
vm-k8s-w1
vm-k8s-w2

[k8s_cluster:children]
master
workers

[all:vars]
ansible_user=ec2-user
ansible_become=true
ansible_become_method=sudo
ansible_ssh_private_key_file=~/.ssh/id_rsa
